version: '3'
services:
  gnostr-gnit:
    build: .
    image: ghcr.io/gnostr-org/gnostr-gnit:main
    volumes:
      - $PWD:/git
      - /nix:/nix
    ports:
      - 3333:8000
    restart: unless-stopped
