site_name: Rusty Web
site_description: Rusty Web is a lightweight web framework for rust developers.
repo_url: https://github.com/tejmagar/rusty-web
edit_uri: ./edit/main/docs
google_analytics: [ 'G-8C90HL047B', 'Rusty Web' ]

nav:
  - Getting Started: index.md
  - Advanced Usage: advanced/index.md
  - Default Limits: default-limits/index.md

theme:
  name: material
  favicon: img/favicon.ico
  features:
    - navigation.expand
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy