name = "gnostr.org"
port = 2222

hostname = "gnostr.org"

[users.gnostr]
is_admin = true
public_key = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDSrJbe2ogeU9YRy3EaprNsVpRJGE2bU0bTPpfMbaymglb+Zju+dQHKdSd5aHy5Yjshyym4PUrt+TtZigdv+Lk3thwgGVZnTA0lpvqWgUAR6aRmhZIzbzzY4wew9Lqc0fG6IUSznRlskn91dz6DAkGx5vOosHqbh4JCHh/MWkAeDsScQq+CjseWtJjtQn/ded4y8e/t9/BvRK7QKcCUf1REUaU8gYSEiLgAkRY4QrqTKLya7ZiGZiK+vfPPo8IUE/rh7+vDUU7XXela3hkf9KSom2gXaemNzB3Q6yDBLBDs0cAYmQhEVv7GuaCC4EtTPBIUYU+5GYQ1zrxgc47nnyMi3KSVVLsuCTRTZnZNldS2VMEcYjTHY1nQip6KQ1RT9AmJ7tJ6e6ZHzP2z94FULek1jByZTnoe7rMhBNzrs7mC9FQk+rG+jAd8C8S8hsssWVWl58AtjGIg31CIT4pmFwYxaLnFGlINYYyYT5/ySEZbEqj+BqNSkxsGgDdIauxoTQFFWhESktMTbrTZd1suyY5Hr8yRk2E683QBR1zgjVz8hmuVwXx14JmG25vpq0EpTCAzq1lHbK1q6ZTP5hGb8ZA6VFL69hxQjHIhcyYvT/3XbWsEa348UdaNb/vtYFmVNiatqhXpHOCxso+FePlL9lAYBJKK8L+i3/eYdMvwfMnVCw== randy.lee.mcmillan@gmail.com"

[users.gnostr-user]
can_create_repos = true
public_key = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDSrJbe2ogeU9YRy3EaprNsVpRJGE2bU0bTPpfMbaymglb+Zju+dQHKdSd5aHy5Yjshyym4PUrt+TtZigdv+Lk3thwgGVZnTA0lpvqWgUAR6aRmhZIzbzzY4wew9Lqc0fG6IUSznRlskn91dz6DAkGx5vOosHqbh4JCHh/MWkAeDsScQq+CjseWtJjtQn/ded4y8e/t9/BvRK7QKcCUf1REUaU8gYSEiLgAkRY4QrqTKLya7ZiGZiK+vfPPo8IUE/rh7+vDUU7XXela3hkf9KSom2gXaemNzB3Q6yDBLBDs0cAYmQhEVv7GuaCC4EtTPBIUYU+5GYQ1zrxgc47nnyMi3KSVVLsuCTRTZnZNldS2VMEcYjTHY1nQip6KQ1RT9AmJ7tJ6e6ZHzP2z94FULek1jByZTnoe7rMhBNzrs7mC9FQk+rG+jAd8C8S8hsssWVWl58AtjGIg31CIT4pmFwYxaLnFGlINYYyYT5/ySEZbEqj+BqNSkxsGgDdIauxoTQFFWhESktMTbrTZd1suyY5Hr8yRk2E683QBR1zgjVz8hmuVwXx14JmG25vpq0EpTCAzq1lHbK1q6ZTP5hGb8ZA6VFL69hxQjHIhcyYvT/3XbWsEa348UdaNb/vtYFmVNiatqhXpHOCxso+FePlL9lAYBJKK8L+i3/eYdMvwfMnVCw== randy.lee.mcmillan@gmail.com"

# Optional.
welcome_message = "welcome to gnostr.org!"
